### ISSUE TITLE
Row colors not working in tabu

### ISSUE THREAD

**Issue by rakeshkasinathan** [tabu-fixed/tabu#20] opened 2019-06-11 13:31 UTC
Hi Everyone,

Row colors not working when using tabu package, find the minimum working example text below:

\documentclass{book}

\usepackage{tabu}
\usepackage[table]{xcolor}
\usepackage{makecell,interfaces-makecell}
\begin{document}

\taburowcolors 5{green!25 .. yellow!50}
\begin{tabu}{X[-1]X}
\repeatcell2{
rows=10,
text/col1=test,
text/col2={Rownumber
\row$=$\thetaburow},
}
\end{tabu} 

\end{document}

**Desired output:**
![Desired](https://user-images.githubusercontent.com/731235/59277829-7b112580-8c7e-11e9-9c34-ec27d1f73219.png)

**Output from tabu:**
![Tabu_output](https://user-images.githubusercontent.com/731235/59277885-9a0fb780-8c7e-11e9-94c4-0654530efb57.png)

**Comment by muzimuzhi** [comment] 2019-06-12 07:14
Duplicate of #1 (and many other opened issues).

**Comment by davidcarlisle** [comment] 2019-06-12 09:24
closing as duplicate

**Closed by davidcarlisle** 2019-06-12 09:24 UTC
