### ISSUE TITLE
Regression with columncolor

### ISSUE THREAD

**Issue by He-Ro** [tabu-fixed/tabu#11] opened 2019-02-08 12:37 UTC
I have the following TeX document:
```tex
\documentclass{article}
\listfiles

\usepackage{colortbl}
\usepackage{longtable}
\usepackage{tabu}
\usepackage{xcolor}

\definecolor{yyy}{RGB}{230,15,110}

\begin{document}
\begin{longtabu}{>{\raggedleft}p{2.5cm} >{\columncolor{yyy}[0.5pt]}X} %
\everyrow{\tabucline[5pt white]-} %
        Test & Test2\\
\end{longtabu} %
\end{document}
```

Under Debian Rolling release with texlive version 2018.20190131-1 which has version 2.9 of tabu the document does not compile and gives the following error:
```log
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tabu/tabu.sty
(/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (./mwe.aux)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
! Undefined control sequence.
<template> ...{1.0}}\tabu@celllalign \columncolor 
                                                  {yyy}[0.5pt]\tabu@cellleft...
l.15 \end{longtabu}
                    %
? X
No pages of output.
Transcript written on mwe.log.
```
If I copy the `tabu.sty` file with version 2.8 into the directory it compiles and generates the expected PDF. The log is the following:
```log
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty) (./tabu.sty
(/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (./mwe.aux)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./mwe.aux)

 *File List*
 article.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
colortbl.sty    2018/12/12 v1.0d Color table columns (DPC)
   array.sty    2018/12/30 v2.4k Tabular extension package (FMi)
   color.sty    1999/02/16
   color.cfg    2016/01/02 v1.6 sample color configuration
  pdftex.def    2018/01/08 v1.0l Graphics/color driver for pdftex
longtable.sty    2014/10/28 v4.11 Multi-page Table package (DPC)+ FMi change
    tabu.sty    2011/02/26 v2.8 - flexible LaTeX tabulars (FC)
varwidth.sty    2009/03/30 ver 0.92;  Variable-width minipages
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
supp-pdf.mkii
 ***********

 )</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on mwe.pdf (1 page, 11060 bytes).
Transcript written on mwe.log.
```
If I again remove the `tabu.sty` file and also remove the `\columncolor{yyy}[0.5pt]` part of the document, it compiles again with the following log:
```log
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tabu/tabu.sty
(/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (./mwe.aux)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./mwe.aux)

 *File List*
 article.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
colortbl.sty    2018/12/12 v1.0d Color table columns (DPC)
   array.sty    2018/12/30 v2.4k Tabular extension package (FMi)
   color.sty    1999/02/16
   color.cfg    2016/01/02 v1.6 sample color configuration
  pdftex.def    2018/01/08 v1.0l Graphics/color driver for pdftex
longtable.sty    2014/10/28 v4.11 Multi-page Table package (DPC)+ FMi change
    tabu.sty    2019/01/11 v2.9 - flexible LaTeX tabulars (FC+tabu-fixed)
varwidth.sty    2009/03/30 ver 0.92;  Variable-width minipages
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
supp-pdf.mkii
 ***********

 )</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on mwe.pdf (1 page, 11020 bytes).
Transcript written on mwe.log.
```
If there is anything else that you would need to fix this, I would gladly help!

**Comment by FrankMittelbach** [comment] 2019-02-26 08:58
Root cause is the same as #4. I added a test file so when #4 gets fixed this should resolve too.

**Comment by FrankMittelbach** [comment] 2019-06-12 10:30
closed as duplicate

**Closed by FrankMittelbach** 2019-06-12 10:30 UTC
Labels: bug, duplicate
